"""ROSClaw First Boot configuration generation and merge utilities."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from .workspace import backup_file


@dataclass
class FirstbootConfig:
    """Runtime profile generated by `rosclaw firstboot`."""

    schema_version: str = "1.0"
    generated_by: str = "rosclaw firstboot"
    generated_at: str = ""
    workspace: dict[str, Any] = field(default_factory=dict)
    runtime: dict[str, Any] = field(default_factory=dict)
    event_bus: dict[str, Any] = field(default_factory=dict)
    sandbox: dict[str, Any] = field(default_factory=dict)
    provider: dict[str, Any] = field(default_factory=dict)
    practice: dict[str, Any] = field(default_factory=dict)
    memory: dict[str, Any] = field(default_factory=dict)
    how: dict[str, Any] = field(default_factory=dict)
    know: dict[str, Any] = field(default_factory=dict)
    auto: dict[str, Any] = field(default_factory=dict)
    darwin: dict[str, Any] = field(default_factory=dict)
    mcp: dict[str, Any] = field(default_factory=dict)
    cloud: dict[str, Any] = field(default_factory=dict)
    storage: dict[str, Any] = field(default_factory=dict)
    telemetry: dict[str, Any] = field(default_factory=dict)
    security: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.generated_at:
            self.generated_at = datetime.now(UTC).isoformat().replace("+00:00", "Z")

        self._sync_memory_backend()
        self._apply_defaults()

    def _sync_memory_backend(self) -> None:
        """Map legacy memory.backend values to runtime.seekdb_backend."""
        backend = self.memory.get("backend")
        if backend is None:
            return
        # Only map if user has not explicitly set runtime.seekdb_backend.
        if "seekdb_backend" in self.runtime:
            return
        mapping = {
            "local": "sqlite",
            "sqlite": "sqlite",
            "memory": "memory",
            "mysql": "mysql",
            "seekdb": "mysql",
        }
        mapped = mapping.get(backend)
        if mapped:
            self.runtime["seekdb_backend"] = mapped

    def _apply_defaults(self) -> None:
        home = self.workspace.get("home", "~/.rosclaw")

        self.workspace = merge_config(
            self.workspace,
            {
                "home": home,
                "profile": "offline",
                "mode": "local",
                "install_channel": "stable",
                "auto_update": False,
            },
        )

        self.runtime = merge_config(
            self.runtime,
            {
                "enabled": True,
                "robot_id": "sim_ur5e",
                "safety_level": "strict",
                "log_level": "INFO",
                "seekdb_backend": "sqlite",
                "seekdb_path": str(
                    Path(home).expanduser() / "data" / "memory" / "knowledge.sqlite"
                ),
            },
        )

        self.event_bus = merge_config(
            self.event_bus,
            {"backend": "local"},
        )

        self.sandbox = merge_config(
            self.sandbox,
            {
                "enabled": True,
                "backend": "mujoco",
                "firewall_mode": True,
                "require_sim_before_real": True,
                "default_world": "tabletop",
            },
        )

        self.provider = merge_config(
            self.provider,
            {
                "enabled": True,
                "mode": "local",
                "default_llm": None,
                "default_vlm": None,
                "default_vla": None,
                "manifests_dir": str(Path(home).expanduser() / "providers" / "manifests"),
            },
        )

        self.practice = merge_config(
            self.practice,
            {
                "enabled": True,
                "auto_record": True,
                "output_dir": str(Path(home).expanduser() / "artifacts" / "episodes"),
                "formats": {"jsonl": True, "mcap": False, "video": False},
            },
        )

        self.memory = merge_config(
            self.memory,
            {
                "enabled": True,
                "backend": "local",
                "path": str(Path(home).expanduser() / "data" / "memory"),
                "write_failures": True,
                "write_successes": True,
            },
        )

        self.how = merge_config(
            self.how,
            {
                "enabled": True,
                "evidence_trace_enabled": True,
                "cooldown_window": 3,
            },
        )

        self.know = merge_config(
            self.know,
            {"enabled": True, "asset_dir": str(Path(home).expanduser() / "data" / "seekdb")},
        )

        self.auto = merge_config(
            self.auto,
            {
                "enabled": False,
                "require_human_approval": True,
                "allow_code_patch": False,
                "trigger_failure_threshold": 3,
            },
        )

        self.darwin = merge_config(
            self.darwin,
            {
                "enabled": False,
                "seeds": [0, 1, 2],
                "episodes": 50,
            },
        )

        self.mcp = merge_config(
            self.mcp,
            {
                "enabled": True,
                "config_path": str(Path(home).expanduser() / "config" / "mcp.json"),
                "server_command": "rosclaw-mcp",
            },
        )

        self.cloud = merge_config(
            self.cloud,
            {
                "enabled": False,
                "endpoint": None,
                "org_id": None,
                "device_id": None,
                "sync": {
                    "configs": False,
                    "logs": False,
                    "artifacts": False,
                    "memory": False,
                    "anonymous_usage": False,
                },
            },
        )

        self.telemetry = merge_config(
            self.telemetry,
            {
                "enabled": True,
                "anonymous_install_ping": True,
                "install_id": None,
                "user_agent": None,
            },
        )

        self.storage = merge_config(
            self.storage,
            {
                "pool_size": 4,
                "vector_enabled": False,
                "outbox_enabled": False,
                "outbox_max_records": 100_000,
                "outbox_flush_interval_sec": 5.0,
            },
        )

        self.security = merge_config(
            self.security,
            {
                "never_execute_robot_without_confirmation": True,
                "require_firewall_for_real_robot": True,
                "secrets_backend": "env",
            },
        )

    def apply_profile(self, profile: str) -> None:
        """Overlay profile-specific defaults without overwriting existing keys."""
        if profile == "offline":
            self.cloud["enabled"] = False
            self.provider["mode"] = "local"
            self.memory["backend"] = "local"
        elif profile == "cloud":
            self.cloud["enabled"] = True
            self.cloud.setdefault("sync", {})
            self.cloud["sync"]["configs"] = True
            self.provider["mode"] = "hybrid"
        elif profile == "hybrid":
            self.cloud["enabled"] = True
            self.cloud.setdefault("sync", {})
            self.cloud["sync"]["configs"] = True
            self.cloud["sync"]["anonymous_usage"] = True
            self.provider["mode"] = "hybrid"

    def to_dict(self) -> dict[str, Any]:
        """Return cleaned dict with None values removed."""
        return _clean_nones(
            {
                "schema_version": self.schema_version,
                "generated_by": self.generated_by,
                "generated_at": self.generated_at,
                "workspace": self.workspace,
                "runtime": self.runtime,
                "event_bus": self.event_bus,
                "sandbox": self.sandbox,
                "provider": self.provider,
                "practice": self.practice,
                "memory": self.memory,
                "how": self.how,
                "know": self.know,
                "auto": self.auto,
                "darwin": self.darwin,
                "mcp": self.mcp,
                "cloud": self.cloud,
                "telemetry": self.telemetry,
                "storage": self.storage,
                "security": self.security,
            }
        )


def _clean_nones(value: Any) -> Any:
    if isinstance(value, dict):
        return {k: _clean_nones(v) for k, v in value.items() if v is not None}
    if isinstance(value, list):
        return [_clean_nones(v) for v in value]
    return value


def merge_config(existing: dict[str, Any], defaults: dict[str, Any]) -> dict[str, Any]:
    """Deep merge: preserve user keys, overlay defaults only for missing keys."""
    result = dict(existing)
    for key, value in defaults.items():
        if key not in result:
            result[key] = value
        elif isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge_config(result[key], value)
    return result


def generate_rosclaw_yaml(home: Path, config: FirstbootConfig) -> Path:
    """Write the main rosclaw.yaml, backing up any existing file."""
    path = home / "config" / "rosclaw.yaml"
    backup_file(path)

    existing: dict[str, Any] = {}
    if path.exists():
        try:
            existing = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except (yaml.YAMLError, OSError):
            existing = {}

    merged = merge_config(existing, config.to_dict())
    merged["generated_by"] = "rosclaw firstboot"
    merged["generated_at"] = datetime.now(UTC).isoformat().replace("+00:00", "Z")

    path.write_text(
        yaml.safe_dump(merged, default_flow_style=False, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return path


def load_rosclaw_yaml(home: Path) -> dict[str, Any]:
    """Load rosclaw.yaml if it exists, otherwise return empty dict."""
    path = home / "config" / "rosclaw.yaml"
    if not path.exists():
        return {}
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (yaml.YAMLError, OSError):
        return {}


def validate_config(home: Path) -> tuple[bool, list[str]]:
    """Validate the generated rosclaw.yaml schema.

    Returns:
        (is_valid, list of error messages)
    """
    errors: list[str] = []
    path = home / "config" / "rosclaw.yaml"
    if not path.exists():
        return False, ["rosclaw.yaml not found"]

    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        return False, [f"Invalid YAML: {exc}"]

    required_top_level = {"schema_version", "workspace", "runtime", "sandbox"}
    missing = required_top_level - set(data.keys())
    if missing:
        errors.append(f"Missing top-level keys: {sorted(missing)}")

    workspace = data.get("workspace", {})
    if not workspace.get("home"):
        errors.append("workspace.home is required")

    runtime = data.get("runtime", {})
    if not runtime.get("robot_id"):
        errors.append("runtime.robot_id is required")

    return len(errors) == 0, errors
