"""Hardware MCP runtime runner generation.

Creates the per-server runtime configuration and the shared
``~/.rosclaw/mcp/bin/rosclaw-mcp-run`` entry point.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml

from rosclaw.mcp.onboarding.schema import McpManifest


RUNNER_SCRIPT = '''#!/usr/bin/env python3
# Auto-generated by rosclaw mcp. Do not edit manually.
import os
import sys
import yaml

ROSCLAW_HOME = os.environ.get("ROSCLAW_HOME", os.path.expanduser("~/.rosclaw"))
RUNTIME_DIR = os.path.join(ROSCLAW_HOME, "mcp", "runtime")

if len(sys.argv) < 2:
    print("Usage: rosclaw-mcp-run <server-name>", file=sys.stderr)
    sys.exit(2)

SERVER_NAME = sys.argv[1]
CONFIG_PATH = os.path.join(RUNTIME_DIR, f"{SERVER_NAME}.yaml")

if not os.path.exists(CONFIG_PATH):
    print(f"Runtime config not found: {CONFIG_PATH}", file=sys.stderr)
    sys.exit(1)

with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

transport = config.get("transport", {})
cmd = transport.get("command")
args = transport.get("args", [])
env = transport.get("env", {})

full_env = os.environ.copy()
full_env.update(env)

# Resolve command relative to the active virtualenv or PATH.
if cmd and not os.path.isabs(cmd):
    import shutil
    resolved = shutil.which(cmd)
    if resolved:
        cmd = resolved

if not cmd:
    print("No transport command configured.", file=sys.stderr)
    sys.exit(1)

os.execvpe(cmd, [cmd] + args, full_env)
'''


def generate_runtime_config(manifest: McpManifest) -> dict[str, Any]:
    """Build the runtime config dict for a manifest."""
    if manifest.mcp is None:
        raise ValueError(f"Manifest {manifest.id} has no MCP configuration")
    return {
        "id": manifest.id,
        "name": manifest.name,
        "version": manifest.version,
        "server_name": manifest.server_name,
        "transport": manifest.mcp.transport.to_dict(),
        "capabilities": manifest.mcp.capabilities.to_dict(),
        "startup": manifest.mcp.startup.to_dict(),
    }


def write_runtime_config(
    manifest: McpManifest,
    runtime_dir: Path,
) -> Path:
    """Write ``<server_name>.yaml`` to the runtime directory."""
    runtime_dir.mkdir(parents=True, exist_ok=True)
    path = runtime_dir / f"{manifest.server_name}.yaml"
    config = generate_runtime_config(manifest)
    tmp = path.with_suffix(".yaml.tmp")
    tmp.write_text(yaml.safe_dump(config, sort_keys=False, allow_unicode=True), encoding="utf-8")
    tmp.replace(path)
    return path


def write_runner_script(bin_dir: Path) -> Path:
    """Write the shared ``rosclaw-mcp-run`` executable."""
    bin_dir.mkdir(parents=True, exist_ok=True)
    path = bin_dir / "rosclaw-mcp-run"
    tmp = path.with_suffix(".tmp")
    tmp.write_text(RUNNER_SCRIPT, encoding="utf-8")
    tmp.replace(path)
    os.chmod(path, 0o755)
    return path


def ensure_runner(
    manifest: McpManifest,
    home: Path,
) -> tuple[Path, Path]:
    """Ensure runtime config and runner script exist.

    Returns:
        (runtime_config_path, runner_script_path)
    """
    runtime_dir = home / "mcp" / "runtime"
    bin_dir = home / "mcp" / "bin"
    runtime_path = write_runtime_config(manifest, runtime_dir)
    runner_path = write_runner_script(bin_dir)
    return runtime_path, runner_path
