"""Digital Twin for ROSClaw - Trajectory validation and sim-to-real bridge."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

import numpy as np
import torch

if TYPE_CHECKING:
    from rosclaw_sim.mjlab_env import MjlabEnv, MjlabEnvConfig
    from rosclaw_sim.domain_randomization import RandomizationConfig


@dataclass
class DigitalTwinConfig:
    """Configuration for Digital Twin.

    Attributes:
        mjlab_config: Configuration for mjlab environment.
        enable_domain_randomization: Whether to enable domain randomization
            for training robust policies.
        randomization_config: Domain randomization parameters.
        safety_margin: Safety margin for joint limits (0.0-1.0).
        collision_check: Whether to check for collisions.
        max_sim_steps: Maximum simulation steps per trajectory.
    """

    mjlab_config: MjlabEnvConfig | None = None
    enable_domain_randomization: bool = False
    randomization_config: RandomizationConfig | None = None
    safety_margin: float = 0.05  # 5% safety margin
    collision_check: bool = True
    max_sim_steps: int = 10000


@dataclass
class TrajectoryValidationResult:
    """Result of trajectory validation.

    Attributes:
        is_valid: Whether the trajectory is valid (no violations).
        collision_detected: Whether any collision was detected.
        joint_limit_violations: List of joint limit violations.
        self_collision_pairs: List of self-colliding body pairs.
        stability_score: Stability metric (0.0-1.0, higher is better).
        execution_time: Simulated execution time in seconds.
        num_steps: Number of simulation steps.
        final_state: Final robot state after trajectory execution.
        detailed_log: Detailed log of the simulation.
    """

    is_valid: bool
    collision_detected: bool = False
    joint_limit_violations: list[dict] = field(default_factory=list)
    self_collision_pairs: list[tuple[str, str]] = field(default_factory=list)
    stability_score: float = 1.0
    execution_time: float = 0.0
    num_steps: int = 0
    final_state: dict[str, Any] = field(default_factory=dict)
    detailed_log: list[dict] = field(default_factory=list)


class DigitalTwin:
    """Digital Twin for robot trajectory validation and simulation.

    The Digital Twin provides a simulation environment to validate trajectories
    generated by VLA (Vision-Language-Action) models before execution on
    physical robots. It uses mjlab (MuJoCo Warp) for GPU-accelerated simulation.

    Example:
        >>> config = DigitalTwinConfig()
        >>> dt = DigitalTwin(config)
        >>> dt.load_model("so101.urdf")
        >>>
        >>> # Validate a VLA-generated trajectory
        >>> trajectory = vla_model.predict(observation, instruction)
        >>> result = dt.verify_trajectory(trajectory)
        >>>
        >>> if result.is_valid:
        ...     robot.execute(trajectory)
        ... else:
        ...     print(f"Validation failed: {result.joint_limit_violations}")
    """

    def __init__(self, config: DigitalTwinConfig | None = None):
        self.config = config or DigitalTwinConfig()
        self._env: MjlabEnv | None = None
        self._robot_path: Path | None = None
        self._joint_lower_limits: torch.Tensor | None = None
        self._joint_upper_limits: torch.Tensor | None = None
        self._joint_names: list[str] = []

    def load_model(
        self,
        robot_path: str | Path,
        robot_name: str = "robot",
        fix_base: bool = False,
    ) -> None:
        """Load a robot model into the Digital Twin.

        Args:
            robot_path: Path to robot URDF or MJCF file.
            robot_name: Name for the robot entity.
            fix_base: Whether to fix the robot base.
        """
        from rosclaw_sim.mjlab_env import MjlabEnv, MjlabEnvConfig

        self._robot_path = Path(robot_path)

        # Create environment configuration
        env_config = self.config.mjlab_config or MjlabEnvConfig()
        env_config.num_envs = 1  # Digital Twin uses single environment
        env_config.enable_rendering = False

        # Create and initialize environment
        self._env = MjlabEnv(env_config)
        self._env.load_robot(
            robot_path=self._robot_path,
            robot_name=robot_name,
            fix_base=fix_base,
        )
        self._env.initialize()

        # Cache joint limits with safety margin
        self._joint_names = self._env.get_joint_names()
        lower, upper = self._env.get_joint_limits()

        # Apply safety margin
        margin = self.config.safety_margin
        range_vals = upper - lower
        self._joint_lower_limits = lower + margin * range_vals
        self._joint_upper_limits = upper - margin * range_vals

    def verify_trajectory(
        self,
        trajectory: dict[str, np.ndarray | torch.Tensor],
        check_collision: bool | None = None,
        verbose: bool = False,
    ) -> TrajectoryValidationResult:
        """Verify a trajectory for safety and feasibility.

        Args:
            trajectory: Dictionary containing:
                - "joint_positions": Array of shape (T, num_joints) or (num_joints,)
                - "joint_velocities": Optional array of shape (T, num_joints)
                - "timestamps": Optional array of shape (T,)
            check_collision: Override collision checking flag.
            verbose: Whether to log detailed information.

        Returns:
            TrajectoryValidationResult with validation details.
        """
        if self._env is None:
            raise RuntimeError("Must call load_model() before verify_trajectory()")

        check_collision = check_collision if check_collision is not None else self.config.collision_check

        # Extract trajectory data
        joint_positions = self._to_tensor(trajectory.get("joint_positions"))
        joint_velocities = self._to_tensor(trajectory.get("joint_velocities"))

        # Handle single timestep
        if joint_positions.ndim == 1:
            joint_positions = joint_positions.unsqueeze(0)
        if joint_velocities is not None and joint_velocities.ndim == 1:
            joint_velocities = joint_velocities.unsqueeze(0)

        num_steps = joint_positions.shape[0]

        # Reset environment
        self._env.reset()

        # Track validation results
        violations = []
        collision_detected = False
        self_collision_pairs = []
        detailed_log = []

        # Simulate trajectory
        for step in range(min(num_steps, self.config.max_sim_steps)):
            # Set joint positions
            pos = joint_positions[step:step+1]  # Keep batch dim

            if joint_velocities is not None and step < len(joint_velocities):
                vel = joint_velocities[step:step+1]
            else:
                vel = torch.zeros_like(pos)

            # Check joint limits before applying
            limit_violations = self._check_joint_limits(pos[0])
            if limit_violations:
                violations.extend(limit_violations)
                if verbose:
                    detailed_log.append({
                        "step": step,
                        "violations": limit_violations,
                    })

            # Apply to simulation
            self._env.set_robot_state(joint_pos=pos, joint_vel=vel)

            # Step simulation to check physics stability
            action = torch.zeros(1, self._env._action_space.shape[1], device=self._env.device)
            obs, reward, done, info = self._env.step(action)

            # Check for NaN values (instability indicator)
            state = self._env.get_robot_state()
            has_nan = any(
                v.isnan().any() if v is not None else False
                for v in state.values() if isinstance(v, torch.Tensor)
            )

            if has_nan:
                collision_detected = True
                if verbose:
                    detailed_log.append({
                        "step": step,
                        "error": "NaN detected - physics instability",
                    })
                break

            # Check collisions (simplified - can be extended with proper contact detection)
            if check_collision and self._check_collision():
                collision_detected = True
                if verbose:
                    detailed_log.append({
                        "step": step,
                        "error": "Collision detected",
                    })

        # Calculate stability score
        stability_score = self._calculate_stability_score(violations, num_steps)

        # Get final state
        final_state = self._env.get_robot_state()
        final_state = {k: v.cpu().numpy() if v is not None else None for k, v in final_state.items()}

        return TrajectoryValidationResult(
            is_valid=len(violations) == 0 and not collision_detected,
            collision_detected=collision_detected,
            joint_limit_violations=violations,
            self_collision_pairs=self_collision_pairs,
            stability_score=stability_score,
            execution_time=num_steps * self._env.step_dt,
            num_steps=step + 1,
            final_state=final_state,
            detailed_log=detailed_log,
        )

    def rollout_policy(
        self,
        policy: callable,
        initial_state: dict[str, torch.Tensor] | None = None,
        max_steps: int = 1000,
        deterministic: bool = True,
    ) -> dict[str, Any]:
        """Rollout a policy in simulation.

        Args:
            policy: Callable that takes observations and returns actions.
            initial_state: Optional initial state to reset to.
            max_steps: Maximum number of steps to simulate.
            deterministic: Whether policy should be deterministic.

        Returns:
            Dictionary containing rollout data:
                - observations: List of observations
                - actions: List of actions
                - rewards: List of rewards
                - states: List of robot states
                - total_reward: Sum of rewards
                - success: Whether rollout completed successfully
        """
        if self._env is None:
            raise RuntimeError("Must call load_model() before rollout_policy()")

        # Reset environment
        obs = self._env.reset()

        # Set initial state if provided
        if initial_state is not None:
            self._env.set_robot_state(
                joint_pos=initial_state.get("joint_pos"),
                joint_vel=initial_state.get("joint_vel"),
            )

        observations = [obs]
        actions = []
        rewards = []
        states = [self._env.get_robot_state()]

        total_reward = 0.0
        success = True

        for step in range(max_steps):
            # Get action from policy
            with torch.no_grad():
                action = policy(obs, deterministic=deterministic)

            # Step environment
            obs, reward, done, info = self._env.step(action)

            observations.append(obs)
            actions.append(action)
            rewards.append(reward.item())
            states.append(self._env.get_robot_state())
            total_reward += reward.item()

            if done.any():
                break

        return {
            "observations": observations,
            "actions": actions,
            "rewards": rewards,
            "states": states,
            "total_reward": total_reward,
            "success": success,
            "num_steps": len(actions),
        }

    def benchmark_trajectory(
        self,
        trajectory: dict[str, np.ndarray | torch.Tensor],
        num_runs: int = 10,
        enable_randomization: bool | None = None,
    ) -> dict[str, Any]:
        """Benchmark a trajectory with domain randomization.

        Args:
            trajectory: Trajectory to benchmark.
            num_runs: Number of randomized runs.
            enable_randomization: Override randomization flag.

        Returns:
            Benchmark statistics:
                - success_rate: Percentage of successful runs
                - avg_stability: Average stability score
                - worst_case: Worst case scenario result
        """
        enable_randomization = enable_randomization if enable_randomization is not None else self.config.enable_domain_randomization

        results = []
        for _ in range(num_runs):
            # Apply domain randomization if enabled
            if enable_randomization and self.config.randomization_config:
                self._apply_domain_randomization()

            # Validate trajectory
            result = self.verify_trajectory(trajectory, verbose=False)
            results.append(result)

        # Compute statistics
        success_count = sum(1 for r in results if r.is_valid)
        avg_stability = sum(r.stability_score for r in results) / len(results)
        worst_result = min(results, key=lambda r: r.stability_score)

        return {
            "success_rate": success_count / len(results),
            "avg_stability": avg_stability,
            "worst_case": worst_result,
            "all_results": results,
        }

    def close(self) -> None:
        """Close the Digital Twin and free resources."""
        if self._env is not None:
            self._env.close()
            self._env = None

    def _to_tensor(self, data: np.ndarray | torch.Tensor | None) -> torch.Tensor | None:
        """Convert data to torch tensor on correct device."""
        if data is None:
            return None
        if isinstance(data, np.ndarray):
            data = torch.from_numpy(data)
        return data.to(self._env.device, dtype=torch.float32)

    def _check_joint_limits(self, joint_pos: torch.Tensor) -> list[dict]:
        """Check if joint positions are within limits."""
        violations = []

        # Adjust for actuated joints only
        num_joints = min(joint_pos.shape[0], self._joint_lower_limits.shape[0])

        for i in range(num_joints):
            pos = joint_pos[i].item()
            lower = self._joint_lower_limits[i].item()
            upper = self._joint_upper_limits[i].item()

            if pos < lower:
                violations.append({
                    "joint_idx": i,
                    "joint_name": self._joint_names[i] if i < len(self._joint_names) else f"joint_{i}",
                    "limit_type": "lower",
                    "value": pos,
                    "limit": lower,
                    "violation": lower - pos,
                })
            elif pos > upper:
                violations.append({
                    "joint_idx": i,
                    "joint_name": self._joint_names[i] if i < len(self._joint_names) else f"joint_{i}",
                    "limit_type": "upper",
                    "value": pos,
                    "limit": upper,
                    "violation": pos - upper,
                })

        return violations

    def _check_collision(self) -> bool:
        """Check for collisions in simulation.

        This is a simplified collision check. For full collision detection,
        proper contact sensor integration would be needed.
        """
        # Placeholder - would need proper contact detection
        # Can be extended with mjlab contact sensors
        return False

    def _calculate_stability_score(self, violations: list, num_steps: int) -> float:
        """Calculate stability score based on violations."""
        if num_steps == 0:
            return 0.0

        # Fewer violations = higher score
        violation_penalty = len(violations) / max(num_steps, 1)
        return max(0.0, 1.0 - violation_penalty)

    def _apply_domain_randomization(self) -> None:
        """Apply domain randomization to simulation parameters."""
        from rosclaw_sim.domain_randomization import DomainRandomization

        if self.config.randomization_config is None:
            return

        dr = DomainRandomization(self.config.randomization_config)
        dr.apply(self._env)

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()
