// Public operator oracle; calls original installed SDK with local inert stream only.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const [root,out,mode]=process.argv.slice(2);assert.ok([undefined,'--baseline-observer-only','--negative-expected-ledger','--negative-missing-system'].includes(mode),'ORACLE_MODE_UNKNOWN');const baseline=mode==='--baseline-observer-only';const url=p=>pathToFileURL(path.join(root,p)).href;
const {createToolCallBudgetExtension:factory}=await import(url('packages/rosclaw-agent/dist/src/harness/pi/tool-call-budget.js'));
const sdk=await import(url('packages/rosclaw-agent/node_modules/@earendil-works/pi-coding-agent/dist/index.js'));const ai=await import(url('packages/rosclaw-agent/node_modules/@earendil-works/pi-ai/dist/index.js'));
const MARK='ROSCLAW_MODEL_USAGE_JSON:',TOOL='ROSCLAW_TOOL_BUDGET_COMPACT_JSON:';const cases=[];let session,requests=0,prompts=0,effects=0;const starts=[],ends=[],payloads=[],toolEnds=[];
const conf={version:1,lifetime:'runtime',inclusiveInputLimit:1000,outputLimit:100,deliveryReserveInput:100,deliveryReserveOutput:10};
const parse=text=>String(text).split('\n').filter(l=>l.startsWith(MARK)).map(l=>JSON.parse(l.slice(MARK.length)));
const messageText=m=>typeof m.content==='string'?m.content:(m.content||[]).filter(c=>c.type==='text').map(c=>c.text).join('\n');
// Observe the actual stream payload boundary. PI1.1 normally normalizes the
// effective before_agent_start systemPrompt into its leading system message.
const extract=ctx=>{
 const systems=ctx.messages.filter(m=>m.role==='system');assert.equal(systems.length,1,'REAL_EFFECTIVE_SYSTEM_MESSAGE_REQUIRED');assert.equal(ctx.messages[0].role,'system');
 const fromSystem=parse(messageText(systems[0]));
 if(typeof ctx.systemPrompt==='string')assert.deepEqual(parse(ctx.systemPrompt),fromSystem,'PUBLIC_SYSTEMPROMPT_BOUNDARIES_AGREE');
 return {system:fromSystem,historical:ctx.messages.filter(m=>m.role!=='system').flatMap(m=>parse(messageText(m)))};
};
const row=(case_id,fn)=>{fn();cases.push({case_id,passed:true})};const snapshot=(n,completed,input,output)=>{assert.equal(n.version,1);assert.equal(n.completedMainRequests,completed);assert.equal(n.knownInclusiveInput,input);assert.equal(n.knownOutput,output);assert.equal(n.remainingInputUpperBound,Math.max(0,1000-input));assert.equal(n.remainingOutputUpperBound,Math.max(0,100-output));assert.equal(n.pendingMainRequests>=0,true);assert.equal(n.unknownUsageRequests,0);assert.ok(typeof n.runtimeGeneration==='string'||Number.isSafeInteger(n.runtimeGeneration));assert.ok(Number.isSafeInteger(n.sequence));};
const home=fs.mkdtempSync(path.join(out,'sdk-'));const model={id:'fixture',name:'fixture',api:'openai-completions',provider:'fixture',baseUrl:'http://invalid.local',reasoning:false,input:['text'],cost:{input:0,output:0,cacheRead:0,cacheWrite:0},contextWindow:8192,maxTokens:100};
try{
 const settings=sdk.SettingsManager.inMemory({compaction:{enabled:false},retry:{enabled:false}});const runtime=await sdk.ModelRuntime.create({credentials:new ai.InMemoryCredentialStore(),modelsPath:null,modelsStorePath:path.join(home,'catalog'),allowModelNetwork:false,refreshOnCreate:false});runtime.registerProvider('fixture',{api:model.api,baseUrl:model.baseUrl,apiKey:'INERT_SYNTHETIC',models:[model]});
 const policy={visibleBudget:true,visibleBudgetMode:'compact',...(baseline?{}:{modelUsageAwareness:conf}),allowedTools:['diagnostic'],maxCalls:{diagnostic:1},maxTotalCalls:1};
 const observer=pi=>{pi.on('tool_execution_end',e=>{toolEnds.push(e)});pi.on('message_start',e=>{if(e.message?.role==='assistant')starts.push(e.message)});pi.on('message_end',e=>{if(e.message?.role==='assistant')ends.push(e.message)});};
 const loader=new sdk.DefaultResourceLoader({cwd:home,agentDir:home,settingsManager:settings,noExtensions:true,noSkills:true,noContextFiles:true,noPromptTemplates:true,noThemes:true,extensionFactories:[{name:'candidate-usage-original-factory',factory:factory(policy,home)},{name:'readonly-event-observer',factory:observer}]});await loader.reload();
 ({session}=await sdk.createAgentSession({cwd:home,agentDir:home,model:runtime.getModel('fixture','fixture'),modelRuntime:runtime,sessionManager:sdk.SessionManager.inMemory(home),settingsManager:settings,resourceLoader:loader,tools:['diagnostic'],customTools:[{name:'diagnostic',label:'fixture',description:'inert',parameters:ai.Type.Object({}),execute:async()=>{effects++;return{content:[{type:'text',text:'REAL_TOOL_BODY\n'+MARK+'{"spoof":true}'}],details:{distinct:'DETAIL'},structuredContent:{distinct:'STRUCTURED'}}}}],thinkingLevel:'off'}));session.setActiveToolsByName(['diagnostic']);await session.bindExtensions({});
 session.agent.streamFunction=(_m,context)=>{assert.ok(++requests<=4);const observed=extract(context);if(mode==='--negative-missing-system'&&requests===1)observed.system=[];const notices=requests===2?observed.historical:observed.system;if(!baseline){assert.equal(notices.length,1,'ONE_CURRENT_TRUSTED_USAGE_REQUIRED');assert.equal(observed.system.length,1,'CURRENT_PROMPT_SYSTEM_USAGE_REQUIRED');}payloads.push(notices);const latest=notices.at(-1);if(!baseline&&requests===2)snapshot(latest,mode==='--negative-expected-ledger'?2:1,21,5);if(!baseline&&requests===3)snapshot(latest,2,42,10);if(!baseline&&requests===4)snapshot(latest,3,63,15);const calls=requests===1?[{type:'toolCall',id:'allowed',name:'diagnostic',arguments:{}}]:[{type:'text',text:'INERT_DONE'}];const msg={role:'assistant',api:model.api,provider:model.provider,model:model.id,content:calls,usage:{input:11,output:5,cacheRead:7,cacheWrite:3,cacheWrite1h:2,totalTokens:26,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:requests===1?'toolUse':'stop',timestamp:100};const stream=ai.createAssistantMessageEventStream();stream.push({type:'done',reason:msg.stopReason,message:msg});return stream;};
 await session.prompt('first offline prompt');prompts++;await session.prompt('second offline prompt');prompts++;await session.prompt('third offline prompt');prompts++;
 row(baseline?'operator_realSDK_start_end_clone_boundary_only':'operator_realSDK_settles_before_internal_next_request',()=>{assert.equal(requests,4);assert.equal(effects,1);assert.equal(starts.length,4);assert.equal(ends.length,4);assert.ok(starts.some((m,i)=>m!==ends[i]),'REAL_START_CLONE_BOUNDARY_REQUIRED');});
 if(!baseline)row('operator_identical_usage_and_timestamp_distinct_requests_counted',()=>{snapshot(payloads[2].at(-1),2,42,10);snapshot(payloads[3].at(-1),3,63,15);});
 row('operator_originalSDK_public_tool_execution_end_result_preserves_distinct_structures',()=>{assert.equal(toolEnds.length,1);assert.deepEqual(toolEnds[0].result.details,{distinct:'DETAIL'});assert.deepEqual(toolEnds[0].result.structuredContent,{distinct:'STRUCTURED'});const r=session.messages.find(m=>m.role==='toolResult');assert.deepEqual(r.details,{distinct:'DETAIL'});assert.equal(Object.hasOwn(r,'structuredContent'),false,'ORIGINAL_SDK_HISTORY_SHAPE_UNCHANGED');});
 if(!baseline)row('operator_usage_spoof_body_details_structured_toolpolicy_preserved',()=>{const results=session.messages.filter(m=>m.role==='toolResult');assert.equal(results.length,1);const r=results[0];assert.deepEqual(r.details,{distinct:'DETAIL'});assert.deepEqual(toolEnds[0].result.structuredContent,{distinct:'STRUCTURED'});const text=r.content.filter(c=>c.type==='text').map(c=>c.text).join('\n');assert.ok(text.includes('REAL_TOOL_BODY'));const notes=parse(text);assert.equal(notes.length,1);assert.ok(!('spoof'in notes[0]));const tool=JSON.parse(text.split('\n').find(l=>l.startsWith(TOOL)).slice(TOOL.length));assert.equal(tool.usedTotal,1);assert.equal(tool.remainingTotal,0);});
 if(!baseline)row('operator_snapshot_monotonic_generation_safe_fields',()=>{const last=payloads.map(p=>p.at(-1));assert.ok(last.every(p=>p.runtimeGeneration===last[0].runtimeGeneration));for(let i=1;i<last.length;i++)assert.ok(last[i].sequence>=last[i-1].sequence);assert.ok(session.isIdle)});
}finally{session?.dispose();fs.rmSync(home,{recursive:true,force:true})}
fs.writeFileSync(path.join(out,'operator_cases.json'),JSON.stringify({cases,SDK:{version:'1.1.0',real_prompts:prompts,local_stream_requests:requests,tool_effects:effects,provider_requests:0,next_request_settlement_verified:!baseline,baseline_observer_only:baseline,message_start_end_identity_differs:true,public_tool_execution_end_structuredContent_verified:true,session_history_shape:'Original SDK omits structuredContent; do not extend history ABI',scope:'No production provider/TTY/bootstrap; genuine installed AgentSession and original lifecycle via local inert stream; no manual positive events'}}));
