cmake_minimum_required(VERSION 3.16)
project(rosclaw_generic_controller_source_parser)
find_package(ament_cmake REQUIRED)
find_package(hardware_interface REQUIRED)
find_package(rcl_yaml_param_parser REQUIRED)
find_package(rcutils REQUIRED)
add_executable(generic_controller_source_parser source_parser.cc)
target_compile_features(generic_controller_source_parser PRIVATE cxx_std_17)
ament_target_dependencies(generic_controller_source_parser hardware_interface rcl_yaml_param_parser rcutils)
