"""
ROSClaw CLI - Command Line Interface

Entry point for the `rosclaw` command.

Commands:
    rosclaw --version          Show version
    rosclaw init [DIR]         Initialize a ROSClaw workspace
    rosclaw run                Start the ROSClaw runtime
    rosclaw start              Alias for run (legacy)
    rosclaw status             Show runtime status
    rosclaw robot list         List available robots
    rosclaw robot install ID   Install/register a robot
    rosclaw robot inspect ID   Show complete robot profile
    rosclaw robot validate ID  Validate e-URDF completeness
    rosclaw practice list      List recorded episodes
    rosclaw practice show ID   Show episode details
    rosclaw practice replay ID Replay episode trace
    rosclaw practice export ID --format json  Export episode metadata
"""

import argparse
import sys
from pathlib import Path


def _version() -> str:
    from rosclaw import __version__

    return __version__


def cmd_init(args: argparse.Namespace) -> int:
    """Initialize a ROSClaw workspace."""
    target = Path(args.dir).resolve()
    target.mkdir(parents=True, exist_ok=True)

    config_path = target / "rosclaw.yaml"
    if config_path.exists() and not args.force:
        print(f"[ROSClaw] Workspace already exists: {target}")
        print("[ROSClaw] Use --force to overwrite config")
        return 1

    config_content = """# ROSClaw Workspace Configuration
# Generated by `rosclaw init`

robot_id: rosclaw_bot
safety_level: MODERATE

# Robot model (e-URDF or MuJoCo XML)
robot_model_path: ""

# Module toggles
enable_firewall: true
enable_memory: true
enable_practice: true
enable_swarm: false

# LLM Provider
llm:
  provider: deepseek
  model: deepseek-chat
  # api_key: set via ROSCLAW_API_KEY env var

# Practice / Timeline
practice:
  output_dir: ./practice_data
  auto_record: true

# SeekDB
memory:
  backend: memory
  # backend: sqlite
  # db_path: ./rosclaw.db
"""
    config_path.write_text(config_content, encoding="utf-8")

    # Create subdirectories
    (target / "practice_data").mkdir(exist_ok=True)
    (target / "skills").mkdir(exist_ok=True)
    (target / "models").mkdir(exist_ok=True)

    print(f"[ROSClaw] Initialized workspace: {target}")
    print(f"[ROSClaw] Config: {config_path}")
    print("[ROSClaw] Next: edit rosclaw.yaml, then run `rosclaw run`")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    """Start the ROSClaw runtime."""
    from rosclaw.core import Runtime, RuntimeConfig

    config = RuntimeConfig(
        robot_id=args.robot_id,
        robot_model_path=args.model_path,
        enable_firewall=args.firewall,
        enable_memory=args.memory,
        enable_practice=args.practice,
        enable_swarm=args.swarm,
    )

    runtime = Runtime(config)

    try:
        runtime.initialize()
        runtime.start()

        print(f"\n[ROSClaw] Runtime started for robot: {args.robot_id}")
        print("[ROSClaw] Press Ctrl+C to stop\n")

        import time

        while runtime.is_running:
            time.sleep(1)

    except KeyboardInterrupt:
        print("\n[ROSClaw] Shutdown requested...")
    finally:
        runtime.stop()

    return 0


def cmd_status(_args: argparse.Namespace) -> int:
    """Show ROSClaw runtime status."""
    import importlib

    config_path = Path("rosclaw.yaml")
    has_config = config_path.exists()

    # Module health checks
    modules = {
        "core.runtime": "Runtime",
        "core.event_bus": "EventBus",
        "firewall.validator": "FirewallValidator",
        "memory.interface": "MemoryInterface",
        "practice.recorder": "PracticeRecorder",
        "sandbox.runtime_adapter": "SandboxRuntimeAdapter",
        "how.engine": "HeuristicEngine",
    }

    health = []
    for mod_name, cls_name in modules.items():
        try:
            mod = importlib.import_module(f"rosclaw.{mod_name}")
            getattr(mod, cls_name)
            health.append((mod_name, "HEALTHY"))
        except (ImportError, AttributeError):
            health.append((mod_name, "DEGRADED"))

    # Overall status
    degraded = [m for m, s in health if s == "DEGRADED"]
    overall = "HEALTHY" if not degraded else "DEGRADED"

    # Output
    print("=" * 50)
    print("ROSClaw v1.0 Status")
    print("=" * 50)
    print(f"Config file:  {'found' if has_config else 'missing'} ({config_path})")
    print(f"Overall:      {overall}")
    print("-" * 50)
    print("Modules:")
    for mod_name, status in health:
        icon = "OK" if status == "HEALTHY" else "DEGRADED"
        print(f"  [{icon}] {mod_name:<30} {status}")
    print("=" * 50)

    if degraded:
        print(f"\nDegraded modules ({len(degraded)}): {', '.join(degraded)}")
        return 1
    return 0


def cmd_robot_list(_args: argparse.Namespace) -> int:
    """List all available robots in the e-URDF-Zoo."""
    from rosclaw.runtime import RobotRegistry

    registry = RobotRegistry()
    available = registry.list_available()
    registered = registry.list()

    print("=" * 50)
    print("ROSClaw e-URDF-Zoo — Robot Registry")
    print("=" * 50)

    if available:
        print(f"\nAvailable robots ({len(available)}):")
        for rid in available:
            status = "[installed]" if rid in registered else "[available]"
            print(f"  {status:<12} {rid}")
    else:
        print("\nNo robots found in e-URDF-Zoo.")
        print("Expected path: e-urdf-zoo/<robot_id>/robot.eurdf.yaml")

    if registered:
        print(f"\nInstalled robots ({len(registered)}):")
        for rid in registered:
            print(f"  [installed]  {rid}")

    print("=" * 50)
    print("\nCommands:")
    print("  rosclaw robot install <robot_id>")
    print("  rosclaw robot inspect <robot_id>")
    print("  rosclaw robot validate <robot_id>")
    return 0


def cmd_robot_install(args: argparse.Namespace) -> int:
    """Install/register a robot from the e-URDF-Zoo."""
    from rosclaw.runtime import RobotRegistry

    registry = RobotRegistry()
    robot_id = args.robot_id

    print(f"[ROSClaw] Installing robot: {robot_id} ...")
    try:
        profile = registry.install(robot_id)
        print(f"[ROSClaw] ✅ Installed: {profile.name} ({profile.robot_id})")
        print(f"[ROSClaw]    Vendor:  {profile.vendor}")
        print(f"[ROSClaw]    DOF:     {profile.embodiment.dof}")
        print(f"[ROSClaw]    Links:   {len(profile.embodiment.links)}")
        print(f"[ROSClaw]    Joints:  {len(profile.embodiment.joints)}")
        print(f"[ROSClaw]    Sensors: {len(profile.embodiment.sensors)}")
        return 0
    except FileNotFoundError as exc:
        print(f"[ROSClaw] ❌ Installation failed: {exc}")
        available = registry.list_available()
        if available:
            print(f"[ROSClaw] Available robots: {', '.join(available)}")
        return 1


def cmd_robot_inspect(args: argparse.Namespace) -> int:
    """Show complete robot profile."""
    import json
    from rosclaw.runtime import RobotRegistry

    registry = RobotRegistry()
    robot_id = args.robot_id

    try:
        profile = registry.inspect(robot_id)
    except FileNotFoundError:
        print(f"[ROSClaw] ❌ Robot '{robot_id}' not found.")
        available = registry.list_available()
        if available:
            print(f"[ROSClaw] Available: {', '.join(available)}")
        return 1

    emb = profile["embodiment"]
    safety = profile["safety"]
    cap = profile["capability"]
    sim = profile["simulation"]
    sem = profile["semantic"]

    print("=" * 60)
    print(f"Robot Profile: {profile['name']} ({profile['robot_id']})")
    print("=" * 60)
    print(f"Vendor:      {profile['vendor']}")
    print(f"Version:     {profile['version']}")
    print(f"Description: {profile['description'].strip()}")
    print()
    print(f"DOF:         {emb['dof']}")
    print(f"Links:       {len(emb['links'])}")
    for link in emb["links"]:
        print(f"  • {link['name']} ({link.get('type', 'link')}, mass={link.get('mass', 0)}kg)")
    print()
    print(f"Joints:      {len(emb['joints'])}")
    for joint in emb["joints"]:
        lim = joint.get("limits", {})
        lim_str = f"[{lim.get('lower', 0):.2f}, {lim.get('upper', 0):.2f}]" if lim else "[-, -]"
        print(f"  • {joint['name']} ({joint['type']}) limits={lim_str}")
    print()
    print(f"Sensors:     {len(emb['sensors'])}")
    for sensor in emb["sensors"]:
        print(f"  • {sensor['name']} ({sensor['type']}) on {sensor.get('parent_link', 'N/A')}")
    print()
    print(f"Actuators:   {len(emb['actuators'])}")
    for act in emb["actuators"]:
        modes = ", ".join(act.get("control_mode", []))
        print(f"  • {act['name']} ({act['type']}) joint={act['joint']} modes=[{modes}]")
    print()
    print("Safety Limits:")
    print(f"  Safety Level: {safety['safety_level']}")
    if safety.get("pfl"):
        print(f"  PFL max TCP force: {safety['pfl'].get('max_tcp_force', 'N/A')} N")
    if safety.get("workspace_boundaries"):
        print(f"  Workspace: {safety['workspace_boundaries'].get('type', 'N/A')}")
    print()
    print("Capabilities:")
    for capability in cap.get("capabilities", []):
        print(f"  • {capability['name']} ({capability['category']}) — {capability.get('description', '')}")
    print()
    print("Simulation Backends:")
    for backend_name, backend_cfg in sim.get("backends", {}).items():
        print(f"  • {backend_name}: {backend_cfg.get('model_file', 'N/A')}")
    print()
    print("Semantic Tags:")
    print(f"  {', '.join(sem.get('semantic_tags', []))}")
    print("=" * 60)

    if args.json:
        print("\n--- JSON Output ---")
        print(json.dumps(profile, indent=2, default=str))

    return 0


def cmd_robot_validate(args: argparse.Namespace) -> int:
    """Validate e-URDF completeness for a robot."""
    from rosclaw.runtime import RobotRegistry

    registry = RobotRegistry()
    robot_id = args.robot_id

    print(f"[ROSClaw] Validating e-URDF for: {robot_id} ...")
    result = registry.validate(robot_id)

    print()
    print("=" * 50)
    print(f"Validation Result: {robot_id}")
    print("=" * 50)
    print(f"Valid: {'✅ YES' if result['valid'] else '❌ NO'}")
    print()

    if result["files_found"]:
        print(f"Files found ({len(result['files_found'])}):")
        for f in result["files_found"]:
            print(f"  ✅ {f}")

    if result["files_missing"]:
        print(f"\nFiles missing ({len(result['files_missing'])}):")
        for f in result["files_missing"]:
            print(f"  ❌ {f}")

    if result["warnings"]:
        print(f"\nWarnings ({len(result['warnings'])}):")
        for w in result["warnings"]:
            print(f"  ⚠️  {w}")

    if result["errors"]:
        print(f"\nErrors ({len(result['errors'])}):")
        for e in result["errors"]:
            print(f"  🚫 {e}")

    print("=" * 50)
    return 0 if result["valid"] else 1


# ------------------------------------------------------------------
# Practice subcommands
# ------------------------------------------------------------------

def _practice_artifacts_dir() -> Path:
    return Path.home() / ".rosclaw" / "artifacts"


def cmd_practice_list(_args: argparse.Namespace) -> int:
    """List all recorded practice episodes."""
    from rosclaw.practice.episode_recorder import EpisodeRecorder

    recorder = EpisodeRecorder("cli", event_bus=None, artifact_base_dir=str(_practice_artifacts_dir()))
    episodes = recorder.list_episodes()

    if not episodes:
        print("No practice episodes found.")
        print(f"Artifact directory: {recorder.artifact_base}")
        return 0

    print("=" * 70)
    print(f"Practice Episodes ({len(episodes)})")
    print("=" * 70)
    print(f"{'Episode ID':<12} {'Status':<12} {'Reward':<8} {'Robot':<15} {'Timestamp'}")
    print("-" * 70)
    for ep in episodes:
        ts = ep.get("timestamp", "N/A")
        if isinstance(ts, (int, float)):
            from datetime import datetime
            ts = datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")
        reward = ep.get("reward")
        reward_str = f"{reward:.2f}" if reward is not None else "N/A"
        print(
            f"{ep['episode_id']:<12} "
            f"{ep.get('status', 'UNKNOWN'):<12} "
            f"{reward_str:<8} "
            f"{ep.get('robot_id', 'N/A'):<15} "
            f"{ts}"
        )
    print("=" * 70)
    print("\nCommands:")
    print("  rosclaw practice show <episode_id>")
    print("  rosclaw practice replay <episode_id>")
    print("  rosclaw practice export <episode_id> --format json")
    return 0


def cmd_practice_show(args: argparse.Namespace) -> int:
    """Show episode details."""
    from rosclaw.practice.episode_recorder import EpisodeRecorder

    recorder = EpisodeRecorder("cli", event_bus=None, artifact_base_dir=str(_practice_artifacts_dir()))
    meta = recorder.get_episode(args.episode_id)

    if meta is None:
        print(f"[ROSClaw] Episode '{args.episode_id}' not found.", file=sys.stderr)
        return 1

    if args.json:
        import json as _json
        print(_json.dumps(meta, indent=2, default=str))
        return 0

    pe = meta.get("praxis_event", {})
    print("=" * 60)
    print(f"Episode: {args.episode_id}")
    print("=" * 60)
    print(f"Robot:     {meta.get('robot_id', 'N/A')}")
    print(f"Status:    {meta.get('status', 'UNKNOWN')}")
    print(f"Reward:    {meta.get('reward', 'N/A')}")
    print(f"Complete:  {'Yes' if meta.get('is_complete') else 'No'}")
    print(f"Duration:  {meta.get('duration_sec', 'N/A')}s")
    print(f"Intent:    {pe.get('agent_instruction', 'N/A')}")
    print(f"Events:    {', '.join(meta.get('received_events', []))}")
    print(f"Artifact:  {recorder.artifact_base / 'episodes' / args.episode_id}")
    print("=" * 60)
    return 0


def cmd_practice_replay(args: argparse.Namespace) -> int:
    """Replay an episode showing all 6 acceptance criteria."""
    from rosclaw.practice.episode_recorder import EpisodeRecorder

    recorder = EpisodeRecorder("cli", event_bus=None, artifact_base_dir=str(_practice_artifacts_dir()))
    meta = recorder.get_episode(args.episode_id)

    if meta is None:
        print(f"[ROSClaw] Episode '{args.episode_id}' not found.", file=sys.stderr)
        return 1

    pe = meta.get("praxis_event", {})

    print("\n" + "=" * 60)
    print(f"REPLAY: Episode {args.episode_id}")
    print("=" * 60)

    # 1. Agent intent
    print("\n1. AGENT INTENT:")
    intent = pe.get("agent_instruction", "N/A")
    print(f"   {intent}")

    # 2. Provider capability
    print("\n2. PROVIDER CAPABILITY SELECTION:")
    trace_path = recorder.artifact_base / "episodes" / args.episode_id / "provider_trace.jsonl"
    if trace_path.exists():
        with open(trace_path, "r", encoding="utf-8") as f:
            traces = [json.loads(line) for line in f if line.strip()]
        for t in traces:
            print(f"   Status: {t.get('status')}, Safe: {t.get('is_safe')}")
    else:
        print("   No provider traces recorded")

    # 3. Sandbox block status
    print("\n3. SANDBOX:")
    if meta.get("sandbox_blocked"):
        print(f"   BLOCKED: {meta.get('sandbox_block_reason', 'Unknown reason')}")
    else:
        print("   No blocks recorded")

    # 4. Runtime execution
    print("\n4. RUNTIME EXECUTION:")
    print(f"   Status: {meta.get('status', 'UNKNOWN')}")
    if meta.get("runtime_error"):
        print(f"   Error:  {meta['runtime_error']}")
    traj_path = recorder.artifact_base / "episodes" / args.episode_id / "trajectory.jsonl"
    if traj_path.exists():
        with open(traj_path, "r", encoding="utf-8") as f:
            traj = [json.loads(line) for line in f if line.strip()]
        print(f"   Trajectory entries: {len(traj)}")

    # 5. Critic judgment
    print("\n5. CRITIC JUDGMENT:")
    print(f"   Reward: {meta.get('reward', 'N/A')}")
    print(f"   Status: {meta.get('status', 'UNKNOWN')}")

    # 6. Memory write
    print("\n6. MEMORY:")
    print(f"   Artifact URI: rosclaw://artifacts/episodes/{args.episode_id}")
    print(f"   SeekDB: Committed via ExperienceCommitter")

    print("\n" + "=" * 60)
    return 0


def cmd_practice_export(args: argparse.Namespace) -> int:
    """Export episode metadata."""
    from rosclaw.practice.episode_recorder import EpisodeRecorder

    recorder = EpisodeRecorder("cli", event_bus=None, artifact_base_dir=str(_practice_artifacts_dir()))
    meta = recorder.get_episode(args.episode_id)

    if meta is None:
        print(f"[ROSClaw] Episode '{args.episode_id}' not found.", file=sys.stderr)
        return 1

    if args.format == "json":
        print(json.dumps(meta, indent=2, default=str))
    else:
        print(f"Unknown format: {args.format}", file=sys.stderr)
        return 1

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="rosclaw",
        description="ROSClaw - Universal OS for Software-Defined Embodied AI",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {_version()}",
    )
    subparsers = parser.add_subparsers(dest="command")

    # init
    init_parser = subparsers.add_parser("init", help="Initialize a ROSClaw workspace")
    init_parser.add_argument("dir", nargs="?", default=".", help="Target directory")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing config")

    # run / start
    for name in ("run", "start"):
        run_parser = subparsers.add_parser(name, help="Start ROSClaw runtime")
        run_parser.add_argument("--robot-id", default="rosclaw_default", help="Robot identifier")
        run_parser.add_argument("--model-path", default=None, help="Path to robot model file")
        run_parser.add_argument(
            "--firewall", action="store_true", default=True, help="Enable Digital Twin Firewall"
        )
        run_parser.add_argument(
            "--memory", action="store_true", default=True, help="Enable Memory module"
        )
        run_parser.add_argument(
            "--practice", action="store_true", default=True, help="Enable Practice recorder"
        )
        run_parser.add_argument(
            "--swarm", action="store_true", default=False, help="Enable Swarm coordination"
        )

    subparsers.add_parser("status", help="Show runtime status")

    # robot subcommand
    robot_parser = subparsers.add_parser("robot", help="Robot registry commands")
    robot_subparsers = robot_parser.add_subparsers(dest="robot_command")

    robot_subparsers.add_parser("list", help="List available robots")

    robot_install_parser = robot_subparsers.add_parser("install", help="Install/register a robot")
    robot_install_parser.add_argument("robot_id", help="Robot identifier (e.g., ur5e)")

    robot_inspect_parser = robot_subparsers.add_parser("inspect", help="Inspect robot profile")
    robot_inspect_parser.add_argument("robot_id", help="Robot identifier")
    robot_inspect_parser.add_argument("--json", action="store_true", help="Output as JSON")

    robot_validate_parser = robot_subparsers.add_parser("validate", help="Validate robot e-URDF")
    robot_validate_parser.add_argument("robot_id", help="Robot identifier")

    # practice subcommand
    practice_parser = subparsers.add_parser("practice", help="Practice episode commands")
    practice_subparsers = practice_parser.add_subparsers(dest="practice_command")

    practice_subparsers.add_parser("list", help="List recorded episodes")

    practice_show_parser = practice_subparsers.add_parser("show", help="Show episode details")
    practice_show_parser.add_argument("episode_id", help="Episode identifier (e.g., ep_0001)")
    practice_show_parser.add_argument("--json", action="store_true", help="Output as JSON")

    practice_replay_parser = practice_subparsers.add_parser("replay", help="Replay episode trace")
    practice_replay_parser.add_argument("episode_id", help="Episode identifier")

    practice_export_parser = practice_subparsers.add_parser("export", help="Export episode metadata")
    practice_export_parser.add_argument("episode_id", help="Episode identifier")
    practice_export_parser.add_argument("--format", choices=["json"], default="json", help="Export format")

    args = parser.parse_args()

    if args.command == "init":
        return cmd_init(args)
    elif args.command in ("run", "start"):
        return cmd_run(args)
    elif args.command == "status":
        return cmd_status(args)
    elif args.command == "robot":
        if args.robot_command == "list":
            return cmd_robot_list(args)
        elif args.robot_command == "install":
            return cmd_robot_install(args)
        elif args.robot_command == "inspect":
            return cmd_robot_inspect(args)
        elif args.robot_command == "validate":
            return cmd_robot_validate(args)
        else:
            robot_parser.print_help()
            return 1
    elif args.command == "practice":
        if args.practice_command == "list":
            return cmd_practice_list(args)
        elif args.practice_command == "show":
            return cmd_practice_show(args)
        elif args.practice_command == "replay":
            return cmd_practice_replay(args)
        elif args.practice_command == "export":
            return cmd_practice_export(args)
        else:
            practice_parser.print_help()
            return 1
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main())
