"""
ROSClaw CLI - Command Line Interface

Entry point for the `rosclaw` command.

Commands:
    rosclaw --version          Show version
    rosclaw init [DIR]         Initialize a ROSClaw workspace
    rosclaw run                Start the ROSClaw runtime
    rosclaw start              Alias for run (legacy)
    rosclaw status             Show runtime status
    rosclaw doctor             Run health diagnosis
    rosclaw logs               Show runtime logs
    rosclaw robot list         List available robots
    rosclaw robot install ID   Install/register a robot
    rosclaw robot inspect ID   Show complete robot profile
    rosclaw robot validate ID  Validate e-URDF completeness
    rosclaw practice list      List recorded episodes
    rosclaw practice show ID   Show episode details
    rosclaw practice replay ID Replay episode trace
    rosclaw practice export ID --format json  Export episode metadata
"""

import argparse
import json
import sys
from pathlib import Path


def _version() -> str:
    from rosclaw import __version__

    return __version__


def cmd_init(args: argparse.Namespace) -> int:
    """Initialize a ROSClaw workspace."""
    target = Path(args.dir).resolve()
    target.mkdir(parents=True, exist_ok=True)

    config_path = target / "rosclaw.yaml"
    if config_path.exists() and not args.force:
        print(f"[ROSClaw] Workspace already exists: {target}")
        print("[ROSClaw] Use --force to overwrite config")
        return 1

    config_content = """# ROSClaw Workspace Configuration
# Generated by `rosclaw init`

robot_id: rosclaw_bot
safety_level: MODERATE

# Robot model (e-URDF or MuJoCo XML)
robot_model_path: ""

# Module toggles
enable_firewall: true
enable_memory: true
enable_practice: true
enable_swarm: false

# LLM Provider
llm:
  provider: deepseek
  model: deepseek-chat
  # api_key: set via ROSCLAW_API_KEY env var

# Practice / Timeline
practice:
  output_dir: ./practice_data
  auto_record: true

# SeekDB
memory:
  backend: memory
  # backend: sqlite
  # db_path: ./rosclaw.db
"""
    config_path.write_text(config_content, encoding="utf-8")

    # Create subdirectories
    (target / "practice_data").mkdir(exist_ok=True)
    (target / "skills").mkdir(exist_ok=True)
    (target / "models").mkdir(exist_ok=True)

    print(f"[ROSClaw] Initialized workspace: {target}")
    print(f"[ROSClaw] Config: {config_path}")
    print("[ROSClaw] Next: edit rosclaw.yaml, then run `rosclaw run`")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    """Start the ROSClaw runtime."""
    from rosclaw.core import Runtime, RuntimeConfig

    config = RuntimeConfig(
        robot_id=args.robot_id,
        robot_model_path=args.model_path,
        enable_firewall=args.firewall,
        enable_memory=args.memory,
        enable_practice=args.practice,
        enable_swarm=args.swarm,
    )

    runtime = Runtime(config)

    try:
        runtime.initialize()
        runtime.start()

        print(f"\n[ROSClaw] Runtime started for robot: {args.robot_id}")
        print("[ROSClaw] Press Ctrl+C to stop\n")

        import time

        while runtime.is_running:
            time.sleep(1)

    except KeyboardInterrupt:
        print("\n[ROSClaw] Shutdown requested...")
    finally:
        runtime.stop()

    return 0


def cmd_doctor(_args: argparse.Namespace) -> int:
    """Deep health diagnosis for ROSClaw runtime and dependencies."""
    import importlib
    import platform

    issues = []
    checks = []

    # 1. Python version
    py_version = platform.python_version()
    py_ok = py_version >= "3.10"
    checks.append(("Python version", py_version, py_ok))
    if not py_ok:
        issues.append(f"Python {py_version} < 3.10 (recommended)")

    # 2. Core modules import
    core_modules = [
        ("rosclaw.core.runtime", "Runtime"),
        ("rosclaw.core.event_bus", "EventBus"),
        ("rosclaw.provider.core.registry", "ProviderRegistry"),
        ("rosclaw.sandbox.runtime_adapter", "SandboxRuntimeAdapter"),
        ("rosclaw.memory.interface", "MemoryInterface"),
        ("rosclaw.practice.episode_recorder", "EpisodeRecorder"),
        ("rosclaw.how.engine", "HeuristicEngine"),
        ("rosclaw.runtime.eurdf_loader", "EURDFLoader"),
    ]
    for mod_name, cls_name in core_modules:
        try:
            mod = importlib.import_module(mod_name)
            getattr(mod, cls_name)
            checks.append((f"Module {mod_name}", "OK", True))
        except Exception as exc:
            checks.append((f"Module {mod_name}", f"FAIL: {exc}", False))
            issues.append(f"Cannot import {mod_name}: {exc}")

    # 3. e-URDF-Zoo accessibility
    zoo_path = Path(__file__).parent.parent.parent / "e-urdf-zoo"
    zoo_ok = zoo_path.exists() and any(zoo_path.iterdir())
    checks.append(("e-URDF-Zoo", str(zoo_path), zoo_ok))
    if not zoo_ok:
        issues.append(f"e-URDF-Zoo not found at {zoo_path}")

    # 4. Config file
    config_path = Path("rosclaw.yaml")
    config_ok = config_path.exists()
    checks.append(("Workspace config", str(config_path), config_ok))
    if not config_ok:
        issues.append("No rosclaw.yaml in current directory. Run `rosclaw init`.")

    # 5. Key dependencies
    deps = ["yaml", "numpy", "pytest", "asyncio"]
    for dep in deps:
        try:
            mod = importlib.import_module(dep)
            ver = getattr(mod, "__version__", "unknown")
            checks.append((f"Dependency {dep}", ver, True))
        except ImportError:
            checks.append((f"Dependency {dep}", "MISSING", False))
            issues.append(f"Python package '{dep}' not installed")

    # 6. GPU / CUDA (optional)
    try:
        import torch
        cuda_ok = torch.cuda.is_available()
        device_count = torch.cuda.device_count() if cuda_ok else 0
        checks.append(("PyTorch CUDA", f"{device_count} device(s)" if cuda_ok else "Not available", cuda_ok))
    except ImportError:
        checks.append(("PyTorch", "Not installed", True))  # optional

    # 7. MuJoCo (optional)
    try:
        import mujoco
        checks.append(("MuJoCo", mujoco.__version__, True))
    except ImportError:
        checks.append(("MuJoCo", "Not installed", True))

    # Output
    print("=" * 60)
    print("ROSClaw v1.0 — Doctor")
    print("=" * 60)
    for name, value, ok in checks:
        icon = "✅" if ok else "❌"
        print(f"  {icon} {name:<30} {value}")
    print("=" * 60)

    if issues:
        print(f"\n⚠️  Issues found ({len(issues)}):")
        for i, issue in enumerate(issues, 1):
            print(f"  {i}. {issue}")
        print("\nRecommendations:")
        if any("e-URDF-Zoo" in i for i in issues):
            print("  • Ensure e-urdf-zoo/ directory exists alongside src/")
        if any("rosclaw.yaml" in i for i in issues):
            print("  • Run: rosclaw init")
        if any("Not installed" in i for i in issues):
            print("  • Install deps: pip install -e .")
        return 1

    print("\n✅ All checks passed. ROSClaw is healthy!")
    return 0


def cmd_logs(args: argparse.Namespace) -> int:
    """Display ROSClaw runtime logs."""
    import glob
    import os
    from datetime import datetime

    log_dir = Path.home() / ".rosclaw" / "logs"
    if not log_dir.exists():
        print(f"[ROSClaw] Log directory not found: {log_dir}")
        print("[ROSClaw] No logs available yet. Start runtime with `rosclaw run`.")
        return 0

    # Collect log files
    pattern = str(log_dir / "*.log")
    log_files = sorted(glob.glob(pattern), key=os.path.getmtime, reverse=True)

    if not log_files:
        print(f"[ROSClaw] No log files in {log_dir}")
        return 0

    # Filter by module if specified
    module_filter = args.module
    if module_filter:
        log_files = [f for f in log_files if module_filter in os.path.basename(f)]

    # Show recent N lines
    tail_lines = args.tail
    level_filter = args.level.upper() if args.level else None

    print("=" * 70)
    print(f"ROSClaw Logs — {log_dir}")
    if module_filter:
        print(f"Module filter: {module_filter}")
    if level_filter:
        print(f"Level filter:  {level_filter}")
    print("=" * 70)

    for log_file in log_files[: args.files]:
        fname = os.path.basename(log_file)
        mtime = datetime.fromtimestamp(os.path.getmtime(log_file)).strftime("%Y-%m-%d %H:%M:%S")
        print(f"\n📄 {fname} (modified {mtime})")
        print("-" * 70)

        try:
            with open(log_file, "r", encoding="utf-8") as f:
                lines = f.readlines()
        except Exception as exc:
            print(f"  [Error reading file: {exc}]")
            continue

        # Filter by level
        if level_filter:
            lines = [ln for ln in lines if level_filter in ln.upper()]

        # Tail
        if tail_lines and len(lines) > tail_lines:
            lines = lines[-tail_lines:]
            print(f"  ... (showing last {tail_lines} lines)")

        for line in lines:
            print(f"  {line.rstrip()}")

    print("\n" + "=" * 70)
    print(f"Total log files: {len(log_files)}")
    print("Commands:")
    print("  rosclaw logs --tail 50          Show last 50 lines")
    print("  rosclaw logs --level ERROR      Filter ERROR lines")
    print("  rosclaw logs --module runtime   Filter by module")
    print("  rosclaw logs --follow           Watch live (not implemented)")
    return 0


def cmd_status(_args: argparse.Namespace) -> int:
    """Show ROSClaw runtime status."""
    import importlib

    config_path = Path("rosclaw.yaml")
    has_config = config_path.exists()

    # Module health checks
    modules = {
        "core.runtime": "Runtime",
        "core.event_bus": "EventBus",
        "firewall.validator": "FirewallValidator",
        "memory.interface": "MemoryInterface",
        "practice.recorder": "PracticeRecorder",
        "sandbox.runtime_adapter": "SandboxRuntimeAdapter",
        "how.engine": "HeuristicEngine",
    }

    health = []
    for mod_name, cls_name in modules.items():
        try:
            mod = importlib.import_module(f"rosclaw.{mod_name}")
            getattr(mod, cls_name)
            health.append((mod_name, "HEALTHY"))
        except (ImportError, AttributeError):
            health.append((mod_name, "DEGRADED"))

    # Overall status
    degraded = [m for m, s in health if s == "DEGRADED"]
    overall = "HEALTHY" if not degraded else "DEGRADED"

    # Output
    print("=" * 50)
    print("ROSClaw v1.0 Status")
    print("=" * 50)
    print(f"Config file:  {'found' if has_config else 'missing'} ({config_path})")
    print(f"Overall:      {overall}")
    print("-" * 50)
    print("Modules:")
    for mod_name, status in health:
        icon = "OK" if status == "HEALTHY" else "DEGRADED"
        print(f"  [{icon}] {mod_name:<30} {status}")
    print("=" * 50)

    if degraded:
        print(f"\nDegraded modules ({len(degraded)}): {', '.join(degraded)}")
        return 1
    return 0


def cmd_robot_list(_args: argparse.Namespace) -> int:
    """List all available robots in the e-URDF-Zoo."""
    from rosclaw.runtime import RobotRegistry

    registry = RobotRegistry()
    available = registry.list_available()
    registered = registry.list()

    print("=" * 50)
    print("ROSClaw e-URDF-Zoo — Robot Registry")
    print("=" * 50)

    if available:
        print(f"\nAvailable robots ({len(available)}):")
        for rid in available:
            status = "[installed]" if rid in registered else "[available]"
            print(f"  {status:<12} {rid}")
    else:
        print("\nNo robots found in e-URDF-Zoo.")
        print("Expected path: e-urdf-zoo/<robot_id>/robot.eurdf.yaml")

    if registered:
        print(f"\nInstalled robots ({len(registered)}):")
        for rid in registered:
            print(f"  [installed]  {rid}")

    print("=" * 50)
    print("\nCommands:")
    print("  rosclaw robot install <robot_id>")
    print("  rosclaw robot inspect <robot_id>")
    print("  rosclaw robot validate <robot_id>")
    return 0


def cmd_robot_install(args: argparse.Namespace) -> int:
    """Install/register a robot from the e-URDF-Zoo."""
    from rosclaw.runtime import RobotRegistry

    registry = RobotRegistry()
    robot_id = args.robot_id

    print(f"[ROSClaw] Installing robot: {robot_id} ...")
    try:
        profile = registry.install(robot_id)
        print(f"[ROSClaw] ✅ Installed: {profile.name} ({profile.robot_id})")
        print(f"[ROSClaw]    Vendor:  {profile.vendor}")
        print(f"[ROSClaw]    DOF:     {profile.embodiment.dof}")
        print(f"[ROSClaw]    Links:   {len(profile.embodiment.links)}")
        print(f"[ROSClaw]    Joints:  {len(profile.embodiment.joints)}")
        print(f"[ROSClaw]    Sensors: {len(profile.embodiment.sensors)}")
        return 0
    except FileNotFoundError as exc:
        print(f"[ROSClaw] ❌ Installation failed: {exc}")
        available = registry.list_available()
        if available:
            print(f"[ROSClaw] Available robots: {', '.join(available)}")
        return 1


def cmd_robot_inspect(args: argparse.Namespace) -> int:
    """Show complete robot profile."""
    import json
    from rosclaw.runtime import RobotRegistry

    registry = RobotRegistry()
    robot_id = args.robot_id

    try:
        profile = registry.inspect(robot_id)
    except FileNotFoundError:
        print(f"[ROSClaw] ❌ Robot '{robot_id}' not found.")
        available = registry.list_available()
        if available:
            print(f"[ROSClaw] Available: {', '.join(available)}")
        return 1

    emb = profile["embodiment"]
    safety = profile["safety"]
    cap = profile["capability"]
    sim = profile["simulation"]
    sem = profile["semantic"]

    print("=" * 60)
    print(f"Robot Profile: {profile['name']} ({profile['robot_id']})")
    print("=" * 60)
    print(f"Vendor:      {profile['vendor']}")
    print(f"Version:     {profile['version']}")
    print(f"Description: {profile['description'].strip()}")
    print()
    print(f"DOF:         {emb['dof']}")
    print(f"Links:       {len(emb['links'])}")
    for link in emb["links"]:
        print(f"  • {link['name']} ({link.get('type', 'link')}, mass={link.get('mass', 0)}kg)")
    print()
    print(f"Joints:      {len(emb['joints'])}")
    for joint in emb["joints"]:
        lim = joint.get("limits", {})
        lim_str = f"[{lim.get('lower', 0):.2f}, {lim.get('upper', 0):.2f}]" if lim else "[-, -]"
        print(f"  • {joint['name']} ({joint['type']}) limits={lim_str}")
    print()
    print(f"Sensors:     {len(emb['sensors'])}")
    for sensor in emb["sensors"]:
        print(f"  • {sensor['name']} ({sensor['type']}) on {sensor.get('parent_link', 'N/A')}")
    print()
    print(f"Actuators:   {len(emb['actuators'])}")
    for act in emb["actuators"]:
        modes = ", ".join(act.get("control_mode", []))
        print(f"  • {act['name']} ({act['type']}) joint={act.get('joint', 'N/A')} modes=[{modes}]")
    print()
    print("Safety Limits:")
    print(f"  Safety Level: {safety['safety_level']}")
    if safety.get("pfl"):
        print(f"  PFL max TCP force: {safety['pfl'].get('max_tcp_force', 'N/A')} N")
    if safety.get("workspace_boundaries"):
        print(f"  Workspace: {safety['workspace_boundaries'].get('type', 'N/A')}")
    print()
    print("Capabilities:")
    for capability in cap.get("capabilities", []):
        category = capability.get("category", capability.get("provider", "skill").split(".")[0])
        print(f"  • {capability['name']} ({category}) — {capability.get('description', '')}")
    print()
    print("Simulation Backends:")
    for backend_name, backend_cfg in sim.get("backends", {}).items():
        print(f"  • {backend_name}: {backend_cfg.get('model_file', 'N/A')}")
    print()
    print("Semantic Tags:")
    print(f"  {', '.join(sem.get('semantic_tags', []))}")
    print("=" * 60)

    if args.json:
        print("\n--- JSON Output ---")
        print(json.dumps(profile, indent=2, default=str))

    return 0


def cmd_robot_validate(args: argparse.Namespace) -> int:
    """Validate e-URDF completeness for a robot."""
    from rosclaw.runtime import RobotRegistry

    registry = RobotRegistry()
    robot_id = args.robot_id

    print(f"[ROSClaw] Validating e-URDF for: {robot_id} ...")
    result = registry.validate(robot_id)

    print()
    print("=" * 50)
    print(f"Validation Result: {robot_id}")
    print("=" * 50)
    print(f"Valid: {'✅ YES' if result['valid'] else '❌ NO'}")
    print()

    if result["files_found"]:
        print(f"Files found ({len(result['files_found'])}):")
        for f in result["files_found"]:
            print(f"  ✅ {f}")

    if result["files_missing"]:
        print(f"\nFiles missing ({len(result['files_missing'])}):")
        for f in result["files_missing"]:
            print(f"  ❌ {f}")

    if result["warnings"]:
        print(f"\nWarnings ({len(result['warnings'])}):")
        for w in result["warnings"]:
            print(f"  ⚠️  {w}")

    if result["errors"]:
        print(f"\nErrors ({len(result['errors'])}):")
        for e in result["errors"]:
            print(f"  🚫 {e}")

    print("=" * 50)
    return 0 if result["valid"] else 1


# ------------------------------------------------------------------
# Practice subcommands
# ------------------------------------------------------------------

def _practice_artifacts_dir() -> Path:
    return Path.home() / ".rosclaw" / "artifacts"


def cmd_practice_list(_args: argparse.Namespace) -> int:
    """List all recorded practice episodes."""
    from rosclaw.practice.episode_recorder import EpisodeRecorder

    recorder = EpisodeRecorder("cli", event_bus=None, artifact_base_dir=str(_practice_artifacts_dir()))
    episodes = recorder.list_episodes()

    if not episodes:
        print("No practice episodes found.")
        print(f"Artifact directory: {recorder.artifact_base}")
        return 0

    print("=" * 70)
    print(f"Practice Episodes ({len(episodes)})")
    print("=" * 70)
    print(f"{'Episode ID':<12} {'Status':<12} {'Reward':<8} {'Robot':<15} {'Timestamp'}")
    print("-" * 70)
    for ep in episodes:
        ts = ep.get("timestamp", "N/A")
        if isinstance(ts, (int, float)):
            from datetime import datetime
            ts = datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")
        reward = ep.get("reward")
        reward_str = f"{reward:.2f}" if reward is not None else "N/A"
        print(
            f"{ep['episode_id']:<12} "
            f"{ep.get('status', 'UNKNOWN'):<12} "
            f"{reward_str:<8} "
            f"{ep.get('robot_id', 'N/A'):<15} "
            f"{ts}"
        )
    print("=" * 70)
    print("\nCommands:")
    print("  rosclaw practice show <episode_id>")
    print("  rosclaw practice replay <episode_id>")
    print("  rosclaw practice export <episode_id> --format json")
    return 0


def cmd_practice_show(args: argparse.Namespace) -> int:
    """Show episode details."""
    from rosclaw.practice.episode_recorder import EpisodeRecorder

    recorder = EpisodeRecorder("cli", event_bus=None, artifact_base_dir=str(_practice_artifacts_dir()))
    meta = recorder.get_episode(args.episode_id)

    if meta is None:
        print(f"[ROSClaw] Episode '{args.episode_id}' not found.", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(meta, indent=2, default=str))
        return 0

    pe = meta.get("praxis_event", {})
    print("=" * 60)
    print(f"Episode: {args.episode_id}")
    print("=" * 60)
    print(f"Robot:     {meta.get('robot_id', 'N/A')}")
    print(f"Status:    {meta.get('status', 'UNKNOWN')}")
    print(f"Reward:    {meta.get('reward', 'N/A')}")
    print(f"Complete:  {'Yes' if meta.get('is_complete') else 'No'}")
    print(f"Duration:  {meta.get('duration_sec', 'N/A')}s")
    print(f"Intent:    {pe.get('agent_instruction', 'N/A')}")
    print(f"Events:    {', '.join(meta.get('received_events', []))}")
    print(f"Artifact:  {recorder.artifact_base / 'episodes' / args.episode_id}")
    print("=" * 60)
    return 0


def cmd_practice_replay(args: argparse.Namespace) -> int:
    """Replay an episode showing all 6 acceptance criteria."""
    from rosclaw.practice.episode_recorder import EpisodeRecorder

    recorder = EpisodeRecorder("cli", event_bus=None, artifact_base_dir=str(_practice_artifacts_dir()))
    meta = recorder.get_episode(args.episode_id)

    if meta is None:
        print(f"[ROSClaw] Episode '{args.episode_id}' not found.", file=sys.stderr)
        return 1

    pe = meta.get("praxis_event", {})

    print("\n" + "=" * 60)
    print(f"REPLAY: Episode {args.episode_id}")
    print("=" * 60)

    # 1. Agent intent
    print("\n1. AGENT INTENT:")
    intent = pe.get("agent_instruction", "N/A")
    print(f"   {intent}")

    # 2. Provider capability
    print("\n2. PROVIDER CAPABILITY SELECTION:")
    trace_path = recorder.artifact_base / "episodes" / args.episode_id / "provider_trace.jsonl"
    if trace_path.exists():
        with open(trace_path, "r", encoding="utf-8") as f:
            traces = [json.loads(line) for line in f if line.strip()]
        for t in traces:
            print(f"   Status: {t.get('status')}, Safe: {t.get('is_safe')}")
    else:
        print("   No provider traces recorded")

    # 3. Sandbox block status
    print("\n3. SANDBOX:")
    if meta.get("sandbox_blocked"):
        print(f"   BLOCKED: {meta.get('sandbox_block_reason', 'Unknown reason')}")
    else:
        print("   No blocks recorded")

    # 4. Runtime execution
    print("\n4. RUNTIME EXECUTION:")
    print(f"   Status: {meta.get('status', 'UNKNOWN')}")
    if meta.get("runtime_error"):
        print(f"   Error:  {meta['runtime_error']}")
    traj_path = recorder.artifact_base / "episodes" / args.episode_id / "trajectory.jsonl"
    if traj_path.exists():
        with open(traj_path, "r", encoding="utf-8") as f:
            traj = [json.loads(line) for line in f if line.strip()]
        print(f"   Trajectory entries: {len(traj)}")

    # 5. Critic judgment
    print("\n5. CRITIC JUDGMENT:")
    print(f"   Reward: {meta.get('reward', 'N/A')}")
    print(f"   Status: {meta.get('status', 'UNKNOWN')}")

    # 6. Memory write
    print("\n6. MEMORY:")
    print(f"   Artifact URI: rosclaw://artifacts/episodes/{args.episode_id}")
    print(f"   SeekDB: Committed via ExperienceCommitter")

    print("\n" + "=" * 60)
    return 0


def cmd_practice_export(args: argparse.Namespace) -> int:
    """Export episode metadata."""
    from rosclaw.practice.episode_recorder import EpisodeRecorder

    recorder = EpisodeRecorder("cli", event_bus=None, artifact_base_dir=str(_practice_artifacts_dir()))
    meta = recorder.get_episode(args.episode_id)

    if meta is None:
        print(f"[ROSClaw] Episode '{args.episode_id}' not found.", file=sys.stderr)
        return 1

    if args.format == "json":
        print(json.dumps(meta, indent=2, default=str))
    else:
        print(f"Unknown format: {args.format}", file=sys.stderr)
        return 1

    return 0


def cmd_provider_list(_args: argparse.Namespace) -> int:
    """List all registered providers."""
    from rosclaw.provider.core.registry import ProviderRegistry

    registry = ProviderRegistry()
    providers = registry.list_providers() if hasattr(registry, "list_providers") else []

    print("=" * 60)
    print("ROSClaw Provider Registry")
    print("=" * 60)
    if providers:
        print(f"{'Name':<20} {'Type':<15} {'Status':<10} {'Description'}")
        print("-" * 60)
        for p in providers:
            print(f"{p.get('name', 'N/A'):<20} {p.get('type', 'N/A'):<15} {p.get('status', 'N/A'):<10} {p.get('description', '')}")
    else:
        print("No providers registered.")
        print("Builtin providers: llm, vlm, vla, vln, world, skill, critic, embedding")
    print("=" * 60)
    return 0


def cmd_skill_list(_args: argparse.Namespace) -> int:
    """List all available skills."""
    from rosclaw.provider.core.registry import ProviderRegistry

    registry = ProviderRegistry()
    skills = registry.list_skills() if hasattr(registry, "list_skills") else []

    print("=" * 60)
    print("ROSClaw Skill Registry")
    print("=" * 60)
    if skills:
        print(f"{'Skill ID':<20} {'Category':<15} {'Provider':<15} {'Description'}")
        print("-" * 60)
        for s in skills:
            print(f"{s.get('skill_id', 'N/A'):<20} {s.get('category', 'N/A'):<15} {s.get('provider', 'N/A'):<15} {s.get('description', '')}")
    else:
        print("No skills registered.")
        print("Builtin skills: pid_move, reach, grasp, navigate, inspect")
    print("=" * 60)
    return 0


def cmd_sandbox_list_worlds(_args: argparse.Namespace) -> int:
    """List available sandbox worlds."""
    print("=" * 60)
    print("ROSClaw Sandbox Worlds")
    print("=" * 60)
    worlds = [
        {"name": "mock", "description": "Mock sandbox for testing (no physics)"},
        {"name": "mujoco", "description": "MuJoCo physics simulation"},
        {"name": "tabletop", "description": "Tabletop manipulation scene"},
        {"name": "empty", "description": "Empty world for unit tests"},
    ]
    print(f"{'Name':<15} {'Description'}")
    print("-" * 60)
    for w in worlds:
        print(f"{w['name']:<15} {w['description']}")
    print("=" * 60)
    return 0


def cmd_sandbox_validate(args: argparse.Namespace) -> int:
    """Validate a robot in sandbox."""
    from rosclaw.runtime import RobotRegistry

    robot_id = args.robot_id
    print(f"[ROSClaw] Validating robot '{robot_id}' in sandbox...")
    registry = RobotRegistry()
    try:
        result = registry.validate(robot_id)
        if result["valid"]:
            print(f"[ROSClaw] ✅ Sandbox validation passed for {robot_id}")
            return 0
        else:
            print(f"[ROSClaw] ❌ Sandbox validation failed for {robot_id}")
            for e in result.get("errors", []):
                print(f"  🚫 {e}")
            return 1
    except Exception as exc:
        print(f"[ROSClaw] ❌ Validation error: {exc}")
        return 1


def cmd_memory_status(_args: argparse.Namespace) -> int:
    """Show memory module status."""
    from rosclaw.memory.interface import MemoryInterface

    mem = MemoryInterface("cli")
    mem._do_initialize()
    stats = mem.get_statistics()
    cap = mem.get_capacity_info()

    print("=" * 60)
    print("ROSClaw Memory Status")
    print("=" * 60)
    print(f"Total experiences:    {stats['total_experiences']}")
    print(f"Success count:        {stats['success_count']}")
    print(f"Failure count:        {stats['failure_count']}")
    print(f"Success rate:         {stats['success_rate']:.1%}")
    print(f"Capacity utilization: {cap['utilization']:.1%}")
    print(f"Age span:             {cap['age_span_days']:.1f} days")
    print("=" * 60)
    return 0


def cmd_memory_query(args: argparse.Namespace) -> int:
    """Query memory for similar experiences."""
    from rosclaw.memory.interface import MemoryInterface

    mem = MemoryInterface("cli")
    mem._do_initialize()
    results = mem.find_similar_experiences(args.query, limit=args.limit)

    print("=" * 60)
    print(f"Memory Query: '{args.query}'")
    print("=" * 60)
    if not results:
        print("No matching experiences found.")
        return 0

    for i, r in enumerate(results, 1):
        print(f"\n[{i}] {r.get('event_type', 'unknown').upper()}")
        print(f"    ID:        {r.get('id', 'N/A')}")
        print(f"    Instruction: {r.get('instruction', 'N/A')[:80]}")
        print(f"    Outcome:   {r.get('outcome', 'N/A')}")
        print(f"    Tags:      {', '.join(r.get('tags', []))}")
    print("=" * 60)
    return 0


def cmd_memory_explain(args: argparse.Namespace) -> int:
    """Explain the most recent failure."""
    from rosclaw.memory.interface import MemoryInterface

    mem = MemoryInterface("cli")
    mem._do_initialize()
    failure = mem.explain_last_failure(task_id=args.task_id)

    print("=" * 60)
    print("ROSClaw Memory — Last Failure Explanation")
    print("=" * 60)
    if failure is None:
        print("No failure records found.")
        return 0

    print(f"Failure ID:    {failure.get('id', 'N/A')}")
    print(f"Failure Type:  {failure.get('failure_type', 'N/A')}")
    print(f"Root Cause:    {failure.get('root_cause', 'N/A')}")
    print(f"Recovery Hint: {failure.get('recovery_hint', 'N/A')}")
    print(f"Sandbox Intervention: {failure.get('sandbox_intervened', False)}")
    print(f"Timestamp:     {failure.get('timestamp', 'N/A')}")
    print("=" * 60)
    return 0


def cmd_events_tail(args: argparse.Namespace) -> int:
    """Tail EventBus events."""
    from rosclaw.core.event_bus import EventBus

    bus = EventBus()
    history = bus.get_history(limit=args.tail)

    print("=" * 70)
    print(f"ROSClaw EventBus — Last {args.tail} events")
    print("=" * 70)
    if not history:
        print("No events in bus history.")
        return 0

    for ev in history:
        ts = getattr(ev, "timestamp", "?")
        topic = getattr(ev, "topic", "?")
        src = getattr(ev, "source", "?")
        print(f"[{ts}] {topic:<40} src={src}")
    print("=" * 70)
    return 0


def cmd_stop(_args: argparse.Namespace) -> int:
    """Stop ROSClaw runtime."""
    import signal
    import os

    pid_file = Path.home() / ".rosclaw" / "runtime.pid"
    if pid_file.exists():
        pid = int(pid_file.read_text().strip())
        try:
            os.kill(pid, signal.SIGTERM)
            print(f"[ROSClaw] Stopped runtime (PID {pid})")
            pid_file.unlink()
            return 0
        except ProcessLookupError:
            print(f"[ROSClaw] Runtime PID {pid} not found")
            pid_file.unlink()
            return 1
    else:
        print("[ROSClaw] No runtime PID file found. Runtime may not be running.")
        return 1


def cmd_restart(args: argparse.Namespace) -> int:
    """Restart ROSClaw runtime."""
    print("[ROSClaw] Restarting runtime...")
    cmd_stop(args)
    import time
    time.sleep(1)
    return cmd_run(args)


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="rosclaw",
        description="ROSClaw - Universal OS for Software-Defined Embodied AI",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {_version()}",
    )
    subparsers = parser.add_subparsers(dest="command")

    # init
    init_parser = subparsers.add_parser("init", help="Initialize a ROSClaw workspace")
    init_parser.add_argument("dir", nargs="?", default=".", help="Target directory")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing config")

    # run / start
    for name in ("run", "start"):
        run_parser = subparsers.add_parser(name, help="Start ROSClaw runtime")
        run_parser.add_argument("--robot-id", default="rosclaw_default", help="Robot identifier")
        run_parser.add_argument("--model-path", default=None, help="Path to robot model file")
        run_parser.add_argument(
            "--firewall", action="store_true", default=True, help="Enable Digital Twin Firewall"
        )
        run_parser.add_argument(
            "--memory", action="store_true", default=True, help="Enable Memory module"
        )
        run_parser.add_argument(
            "--practice", action="store_true", default=True, help="Enable Practice recorder"
        )
        run_parser.add_argument(
            "--swarm", action="store_true", default=False, help="Enable Swarm coordination"
        )

    subparsers.add_parser("status", help="Show runtime status")
    subparsers.add_parser("stop", help="Stop ROSClaw runtime")
    subparsers.add_parser("restart", help="Restart ROSClaw runtime")

    # doctor
    doctor_parser = subparsers.add_parser("doctor", help="Run health diagnosis")

    # logs
    logs_parser = subparsers.add_parser("logs", help="Show runtime logs")
    logs_parser.add_argument("--tail", type=int, default=30, help="Show last N lines (default: 30)")
    logs_parser.add_argument("--level", choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"], help="Filter by log level")
    logs_parser.add_argument("--module", default=None, help="Filter by module name")
    logs_parser.add_argument("--files", type=int, default=5, help="Number of log files to show (default: 5)")

    # events
    events_parser = subparsers.add_parser("events", help="EventBus commands")
    events_parser.add_argument("--tail", type=int, default=20, help="Show last N events")

    # robot subcommand
    robot_parser = subparsers.add_parser("robot", help="Robot registry commands")
    robot_subparsers = robot_parser.add_subparsers(dest="robot_command")

    robot_subparsers.add_parser("list", help="List available robots")

    robot_install_parser = robot_subparsers.add_parser("install", help="Install/register a robot")
    robot_install_parser.add_argument("robot_id", help="Robot identifier (e.g., ur5e)")

    robot_inspect_parser = robot_subparsers.add_parser("inspect", help="Inspect robot profile")
    robot_inspect_parser.add_argument("robot_id", help="Robot identifier")
    robot_inspect_parser.add_argument("--json", action="store_true", help="Output as JSON")

    robot_validate_parser = robot_subparsers.add_parser("validate", help="Validate robot e-URDF")
    robot_validate_parser.add_argument("robot_id", help="Robot identifier")

    # provider subcommand
    provider_parser = subparsers.add_parser("provider", help="Provider commands")
    provider_subparsers = provider_parser.add_subparsers(dest="provider_command")
    provider_subparsers.add_parser("list", help="List registered providers")

    # skill subcommand
    skill_parser = subparsers.add_parser("skill", help="Skill commands")
    skill_subparsers = skill_parser.add_subparsers(dest="skill_command")
    skill_subparsers.add_parser("list", help="List available skills")

    # sandbox subcommand
    sandbox_parser = subparsers.add_parser("sandbox", help="Sandbox commands")
    sandbox_subparsers = sandbox_parser.add_subparsers(dest="sandbox_command")
    sandbox_subparsers.add_parser("list-worlds", help="List available sandbox worlds")
    sandbox_validate_parser = sandbox_subparsers.add_parser("validate", help="Validate robot in sandbox")
    sandbox_validate_parser.add_argument("robot_id", help="Robot identifier")

    # memory subcommand
    memory_parser = subparsers.add_parser("memory", help="Memory commands")
    memory_subparsers = memory_parser.add_subparsers(dest="memory_command")
    memory_subparsers.add_parser("status", help="Show memory status")
    memory_query_parser = memory_subparsers.add_parser("query", help="Query memory")
    memory_query_parser.add_argument("query", help="Query text")
    memory_query_parser.add_argument("--limit", type=int, default=5, help="Max results")
    memory_explain_parser = memory_subparsers.add_parser("explain", help="Explain last failure")
    memory_explain_parser.add_argument("--task-id", default=None, help="Filter by task ID")

    # practice subcommand
    practice_parser = subparsers.add_parser("practice", help="Practice episode commands")
    practice_subparsers = practice_parser.add_subparsers(dest="practice_command")

    practice_subparsers.add_parser("list", help="List recorded episodes")

    practice_show_parser = practice_subparsers.add_parser("show", help="Show episode details")
    practice_show_parser.add_argument("episode_id", help="Episode identifier (e.g., ep_0001)")
    practice_show_parser.add_argument("--json", action="store_true", help="Output as JSON")

    practice_replay_parser = practice_subparsers.add_parser("replay", help="Replay episode trace")
    practice_replay_parser.add_argument("episode_id", help="Episode identifier")

    practice_export_parser = practice_subparsers.add_parser("export", help="Export episode metadata")
    practice_export_parser.add_argument("episode_id", help="Episode identifier")
    practice_export_parser.add_argument("--format", choices=["json"], default="json", help="Export format")

    args = parser.parse_args()

    if args.command == "init":
        return cmd_init(args)
    elif args.command in ("run", "start"):
        return cmd_run(args)
    elif args.command == "status":
        return cmd_status(args)
    elif args.command == "doctor":
        return cmd_doctor(args)
    elif args.command == "logs":
        return cmd_logs(args)
    elif args.command == "robot":
        if args.robot_command == "list":
            return cmd_robot_list(args)
        elif args.robot_command == "install":
            return cmd_robot_install(args)
        elif args.robot_command == "inspect":
            return cmd_robot_inspect(args)
        elif args.robot_command == "validate":
            return cmd_robot_validate(args)
        else:
            robot_parser.print_help()
            return 1
    elif args.command == "provider":
        if args.provider_command == "list":
            return cmd_provider_list(args)
        else:
            provider_parser.print_help()
            return 1
    elif args.command == "skill":
        if args.skill_command == "list":
            return cmd_skill_list(args)
        else:
            skill_parser.print_help()
            return 1
    elif args.command == "sandbox":
        if args.sandbox_command == "list-worlds":
            return cmd_sandbox_list_worlds(args)
        elif args.sandbox_command == "validate":
            return cmd_sandbox_validate(args)
        else:
            sandbox_parser.print_help()
            return 1
    elif args.command == "memory":
        if args.memory_command == "status":
            return cmd_memory_status(args)
        elif args.memory_command == "query":
            return cmd_memory_query(args)
        elif args.memory_command == "explain":
            return cmd_memory_explain(args)
        else:
            memory_parser.print_help()
            return 1
    elif args.command == "events":
        return cmd_events_tail(args)
    elif args.command == "stop":
        return cmd_stop(args)
    elif args.command == "restart":
        return cmd_restart(args)
    elif args.command == "practice":
        if args.practice_command == "list":
            return cmd_practice_list(args)
        elif args.practice_command == "show":
            return cmd_practice_show(args)
        elif args.practice_command == "replay":
            return cmd_practice_replay(args)
        elif args.practice_command == "export":
            return cmd_practice_export(args)
        else:
            practice_parser.print_help()
            return 1
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main())
